/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "../JuceLibraryCode/JuceHeader.h"
#include "MainComponent.h"
#include "TestModule.h"

ApplicationProperties* appProperties = nullptr;

//==============================================================================
class VControlSurfaceDemoApplication  : public JUCEApplication
{
public:
    //==============================================================================
    VControlSurfaceDemoApplication() {}

    const String getApplicationName() override       { return ProjectInfo::projectName; }
    const String getApplicationVersion() override    { return ProjectInfo::versionString; }
    bool moreThanOneInstanceAllowed() override       { return true; }

    //==============================================================================
    void initialise (const String& commandLine) override
    {
        appProperties = new ApplicationProperties();
        
        PropertiesFile::Options opts;
        opts.applicationName            = ProjectInfo::projectName;
        opts.filenameSuffix             = ".xml";
        opts.folderName                 = "prefs";
        opts.osxLibrarySubFolder        = "Application Support/V-Control Pro";
        opts.commonToAllUsers           = false;
        opts.ignoreCaseOfKeyNames       = false;
        opts.doNotSave                  = false;
        opts.millisecondsBeforeSaving   = 5000;
        opts.storageFormat              = PropertiesFile::storeAsXML;
        
        appProperties->setStorageParameters(opts);
        
        test = new TestModule("mixer2", "Neyrinck", "Mixer 2", nullptr);
        VControlModuleSetModuleVendor(test->module, "Neyrinck");
        VControlModuleSetModuleCategory(test->module, kVControlCategory_Distortion);
        VControlModulePublish(test->module);

    }

    void shutdown() override
    {
        test = nullptr;
        delete appProperties;
    }

    //==============================================================================
    void systemRequestedQuit() override
    {
        // This is called when the app is being asked to quit: you can ignore this
        // request and let the app carry on running, or call quit() to allow the app to close.
        quit();
    }

    void anotherInstanceStarted (const String& commandLine) override
    {
        // When another instance of the app is launched while this one is running,
        // this method is invoked, and the commandLine parameter tells you what
        // the other instance's command-line arguments were.
    }

private:
    ScopedPointer<TestModule> test;
};

//==============================================================================
// This macro generates the main() routine that launches the app.
START_JUCE_APPLICATION (VControlSurfaceDemoApplication)
